// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230427142934_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApi.Models.Electrician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeePerHour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwnShop")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadiusMaxToWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServicesOfBrends")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Electricians");
                });

            modelBuilder.Entity("WebApi.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ElectricianId")
                        .HasColumnType("int");

                    b.Property<int>("FeedBack")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectricianId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("WebApi.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ElectricianId")
                        .HasColumnType("int");

                    b.Property<string>("NameOfSkill")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ElectricianId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("WebApi.Models.Feedback", b =>
                {
                    b.HasOne("WebApi.Models.Electrician", "Electrician")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ElectricianId");

                    b.Navigation("Electrician");
                });

            modelBuilder.Entity("WebApi.Models.Skill", b =>
                {
                    b.HasOne("WebApi.Models.Electrician", "Electrician")
                        .WithMany("ScillsList")
                        .HasForeignKey("ElectricianId");

                    b.Navigation("Electrician");
                });

            modelBuilder.Entity("WebApi.Models.Electrician", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("ScillsList");
                });
#pragma warning restore 612, 618
        }
    }
}
